services:
  - type: web
    name: bagisto
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: APP_NAME
        value: Bagisto
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_ADMIN_URL
        value: admin
      - key: APP_TIMEZONE
        value: Asia/Kolkata
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_CURRENCY
        value: USD
      - key: APP_KEY
        sync: false
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: FILESYSTEM_DISK
        value: public
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: MAIL_MAILER
        value: bagisto-dynamic-smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: Shop
      - key: RUN_MIGRATIONS
        value: true
      - key: RUN_SEEDERS
        value: false
